# Generated by Django 4.2.7 on 2023-11-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('audio', models.FileField(upload_to='audios/')),
                ('video', models.FileField(upload_to='videos/')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.museum')),
            ],
        ),
    ]
