# Generated by Django 4.2.7 on 2023-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbs/'),
        ),
    ]
