# Generated by Django 4.2.7 on 2023-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exhibit_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='audio',
            field=models.FileField(upload_to='../static/audios/'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='../static/thumbs/'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='video',
            field=models.FileField(upload_to='../static/videos/'),
        ),
    ]
