# Generated by Django 4.2.7 on 2023-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exhibit_audio_alter_exhibit_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
