# Generated by Django 5.0.1 on 2024-01-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sidd',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
