# Generated by Django 5.0.1 on 2024-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_sidd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pasd',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
