# Generated by Django 5.0.1 on 2024-01-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_pasd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='nump',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sidd',
        ),
    ]
