# Generated by Django 5.0.1 on 2024-01-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_employee_nump_remove_employee_sidd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('coor', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='mems',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='coor',
            new_name='nump',
        ),
        migrations.AddField(
            model_name='device',
            name='pasd',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
