# Generated by Django 5.0.1 on 2024-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_robot_remove_team_mems_rename_coor_device_nump_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='urln',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
