# Generated by Django 5.0.1 on 2024-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_device_firs'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lati',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='long',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
