# Generated by Django 5.0.1 on 2024-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_device_lati_device_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='plat',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
