# Generated by Django 5.0.1 on 2024-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_device_plat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='coor',
            new_name='lati',
        ),
        migrations.AddField(
            model_name='robot',
            name='long',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
