# Generated by Django 5.0.1 on 2024-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_coor_robot_lati_robot_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='perc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
