# Generated by Django 5.0.1 on 2024-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_robot_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='perc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
