# Generated by Django 5.0.1 on 2024-02-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_robot_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='fpsf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
