# Generated by Django 5.0.1 on 2024-02-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_robot_fpsf'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='f1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='f2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
